import '../styles/index.scss';
import '../assets/main.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <main className='container-app'>
          {children}
        </main>
      </body>
        
    </html>
  )
}
